<script setup lang="ts">
import { computed, ref, onMounted, onBeforeUnmount } from 'vue'
import { LayoutDashboard, CalendarDays, ClipboardList, Wallet, Users, Inbox, SlidersHorizontal, Settings, Bell, Leaf, LogOut, X, ChartNoAxesCombined } from 'lucide-vue-next'
import EmployeeAvatar from './EmployeeAvatar.vue'
import { useSession } from '../stores/session'
import { logout } from '../services/auth'
const session=useSession()
const mobile=ref(window.innerWidth<=760)
const resize=()=>mobile.value=window.innerWidth<=760
onMounted(()=>window.addEventListener('resize',resize))
onBeforeUnmount(()=>window.removeEventListener('resize',resize))
const primary=[{to:'/',label:'Overview',icon:LayoutDashboard},{to:'/requests',label:'My requests',icon:ClipboardList},{to:'/balances',label:'Leave balances',icon:Wallet},{to:'/calendar',label:'Team calendar',icon:CalendarDays}]
const management=computed(()=>[{to:'/approvals',label:'Approval inbox',icon:Inbox,show:session.has('MANAGER','HR')},{to:'/team',label:'My team',icon:Users,show:session.has('MANAGER')},{to:'/employees',label:'Employees',icon:Users,show:session.has('HR','ADMIN')},{to:'/policies',label:'Policies & holidays',icon:SlidersHorizontal,show:session.has('HR','ADMIN')},{to:'/reports',label:'Reports',icon:ChartNoAxesCombined,show:session.has('HR','MANAGER')},{to:'/settings',label:'Settings',icon:Settings,show:session.has('ADMIN')}].filter(n=>n.show))
</script>
<template><div v-if="session.sidebarOpen" class="sidebar-scrim" @click="session.sidebarOpen=false"/><aside class="sidebar" :class="{open:session.sidebarOpen}" :inert="mobile&&!session.sidebarOpen"><RouterLink to="/" class="brand"><span class="brand-mark">w</span>workleave<span class="brand-period">.</span></RouterLink><button class="icon-btn mobile-close" aria-label="Close navigation" @click="session.sidebarOpen=false"><X/></button><div class="workspace-switch"><span class="workspace-icon"><Leaf :size="17"/></span><div><strong>Your workspace</strong><small>Space for work & life</small></div><span class="workspace-dot"/></div><div class="nav-heading">WORKSPACE</div><nav aria-label="Main navigation"><RouterLink v-for="item in primary" :key="item.to" :to="item.to" class="nav-item" :exact-active-class="'active'" @click="session.sidebarOpen=false"><component :is="item.icon" :size="19"/>{{item.label}}</RouterLink><template v-if="management.length"><div class="nav-heading management-heading">MANAGEMENT</div><RouterLink v-for="item in management" :key="item.to" :to="item.to" class="nav-item" exact-active-class="active" @click="session.sidebarOpen=false"><component :is="item.icon" :size="19"/>{{item.label}}</RouterLink></template></nav><div class="sidebar-bottom"><RouterLink to="/notifications" class="nav-item" exact-active-class="active" @click="session.sidebarOpen=false"><Bell :size="19"/>Notifications</RouterLink><div class="sidebar-note"><Leaf :size="22"/><strong>A little balance goes a long way.</strong><span>Make time for what matters.</span></div><div class="account"><RouterLink to="/profile" class="account-link" @click="session.sidebarOpen=false"><EmployeeAvatar :name="`${session.user?.first_name} ${session.user?.last_name}`"/><div><strong>{{session.user?.first_name}} {{session.user?.last_name}}</strong><small>{{session.user?.team}}</small></div></RouterLink><button class="icon-btn" aria-label="Sign out" @click="logout()"><LogOut :size="17"/></button></div></div></aside></template>
