<script setup lang="ts">
import { reactive, ref, watch } from 'vue'
import { useApi, refreshData } from '../composables/query'
import { patch, post } from '../services/api'
import { useSession } from '../stores/session'
import type { Lookup } from '../types'
import AsyncState from '../components/AsyncState.vue'
import DataTable from '../components/DataTable.vue'
const session=useSession(),{data,loading,error,refresh}=useApi<{id:number;name:string;timezone:string;retention_years:number}>('/settings'), departments=useApi<Lookup[]>('/departments'),teams=useApi<Lookup[]>('/teams'),audit=useApi<Record<string,unknown>[]>('/audit')
const form=reactive({name:'',timezone:'',retention_years:5}),dept=reactive({name:'',description:''}),team=reactive({name:'',department_id:1}),failure=ref(''),busy=ref(false)
watch(data,value=>{if(value)Object.assign(form,{name:value.name,timezone:value.timezone,retention_years:value.retention_years})},{immediate:true})
async function save(path:string,body:unknown,method='POST'){busy.value=true;failure.value='';try{await(method==='PATCH'?patch(path,body):post(path,body));await refreshData();session.message('Settings saved.');dept.name='';team.name=''}catch(e){failure.value=(e as Error).message}finally{busy.value=false}}
</script>
<template><div class="page-heading"><div><div class="eyebrow">YOUR ORGANIZATION</div><h1>Workspace settings</h1><p>A solid foundation for your people.</p></div></div><p v-if="failure" class="error-box" role="alert">{{failure}}</p><AsyncState :loading="loading" :error="error" @retry="refresh"><div class="policy-columns"><form class="panel form-panel" @submit.prevent="save('/settings',form,'PATCH')"><h2>Organization</h2><label>Organization name<input v-model="form.name" required></label><label>Default timezone<input v-model="form.timezone" required></label><label>Retention policy (years)<input v-model.number="form.retention_years" type="number" min="1" max="50" required></label><p class="field-hint">This records the organization’s retention policy. Follow the documented retention procedure before deleting records.</p><button class="btn primary" :disabled="busy">Save settings</button></form><div class="panel form-panel"><form @submit.prevent="save('/departments',dept)"><h2>Departments</h2><p class="muted">{{departments.data.value?.map(d=>d.name).join(' · ')}}</p><label>New department<input v-model="dept.name" required></label><button class="btn secondary" :disabled="busy">Add department</button></form><div class="summary-divider"/><form @submit.prevent="save('/teams',team)"><h2>Teams</h2><label>New team<input v-model="team.name" required></label><label>Department<select v-model.number="team.department_id"><option v-for="d in departments.data.value" :value="d.id">{{d.name}}</option></select></label><button class="btn secondary" :disabled="busy">Add team</button></form></div></div></AsyncState><section class="panel"><div class="section-heading"><h2>Operational audit trail</h2><span class="muted">Most recent 50 events</span></div><AsyncState :loading="audit.loading.value" :error="audit.error.value" @retry="audit.refresh"><DataTable :headers="['Time','Actor ID','Action','Entity']"><tr v-for="entry in audit.data.value" :key="String(entry.id)"><td>{{new Date(String(entry.timestamp)).toLocaleString()}}</td><td>{{entry.actor_id||'System'}}</td><td>{{entry.action}}</td><td>{{entry.entity_type}} #{{entry.entity_id}}</td></tr></DataTable></AsyncState></section></template>
